version: "3.5"

services:
  lab:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    environment:
      - JUPYTER_CONFIG_DIR=./.jupyter
    ports:
      - "8888:8888"
    command:
      jupyter lab
        --ip=0.0.0.0
        --allow-root
        --no-browser
